In [1]:
# Difference between a normal list to a numpy array in python

import numpy as np
import time
import sys
SIZE = 1000000
l1 = range(SIZE)
l2 = range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)

# python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)
# numpy array
start= time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)



python list took:  142.6692008972168
numpy took:  17.951488494873047


In [2]:
# array creation through numpy 
import numpy as np

a=np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
import numpy as np
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
#using normal for loop for traversing across the elements

for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [9]:
# using flatten fn
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [13]:
# numpy nditer - for iterating through numpy array's

b = np.nditer(a,order='F')
b

In [14]:
for i in b:
    print(i)

0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15


In [17]:
b = np.nditer(a , flags=['external_loop'],order = 'F')
for each_i in b:
    print(each_i)

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [34]:
# Modify array values while iterating

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

for x in np.nditer(a , op_flags=['readwrite']):
    x[...]= x*x

In [35]:
a

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [37]:
# Iterate two broadcastable arrays concurrently

b= np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [38]:
x = np.nditer([a,b])

In [39]:
x

In [40]:
print(x)

In [44]:
for x,y in np.nditer([a,b]):
    print(x,y)

1 3
4 3
9 3
16 7
25 7
36 7
49 11
64 11
81 11


For more Resources and exercises and practise check out :- https://www.labri.fr/perso/nrougier/from-python-to-numpy/ 

Complete the assignments in the above source