In [1]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances

In [3]:
cosine_similarity([[43,33]],[[55,23]])

array([[0.96677724]])

In [4]:
doc1 = """
iphone sales contributed to 70% of revenue. iphone demand is increasing by 20% yoy. 
the main competitor phone galaxy recorded 5% less growth compared to iphone"
"""

doc2 = """
The upside pressure on volumes for the iPhone 12 series, historical outperformance 
in the July-September time period heading into launch event, and further catalysts in relation
to outperformance for iPhone 13 volumes relative to lowered investor expectations implies a 
very attractive set up for the shares.
"""

doc3 = """
samsung's flagship product galaxy is able to penetrate more into asian markets compared to
iphone. galaxy is redesigned with new look that appeals young demographics. 60% of samsung revenues
are coming from galaxy phone sales
"""

doc4 = """
Samsung Electronics unveils its Galaxy S21 flagship, with modest spec improvements 
and a significantly lower price point. Galaxy S21 price is lower by ~20% (much like the iPhone 12A), 
which highlights Samsung's focus on boosting shipments and regaining market share.
"""

In [5]:
import pandas as pd

df = pd.DataFrame([
        {'iPhone': 3,'galaxy': 1},
        {'iPhone': 2,'galaxy': 0},
        {'iPhone': 1,'galaxy': 3},
        {'iPhone': 1,'galaxy': 2},
    ],
    index=[
        "doc1",
        "doc2",
        "doc3",
        "doc4"
    ])

df

galaxy  iPhone
doc1       1       3
doc2       0       2
doc3       3       1
doc4       2       1

In [11]:
cosine_similarity(df.loc['doc1':'doc1'],df.loc['doc4':'doc4'])

array([[0.70710678]])

In [9]:
cosine_distances(df.loc['doc1':'doc1'],df.loc['doc2':'doc2'])

array([[0.0513167]])

In [16]:
pip install tensorflow


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\ntuse\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [18]:
pip install numpy --upgrade

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\ntuse\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [20]:
# #cosine similarity through tensorflow
# import tensorflow as tf

# # Initialize the metric
# m = tf.keras.metrics.CosineSimilarity(axis=1)

# # Update the state of the metric with example data
# m.update_state([[0., 1.], [1., 1.]], [[1., 0.], [1., 1.]])

# # Get the result
# result = m.result().numpy()
# print(result) # Output: 0.49999997
